export const USERS = [
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "Տոնսեր",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "Տոնսեր",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "Արտագնա",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "Տոնսեր",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    },
    {
        name: "Գագիկ Մագիկյան +37491112113",
        type: "Տոնսեր",
        service: "",
        time: 123,
        stageType: "Processing",
        stageShape: "treangle",
        stageNumber: "1.9",
    }
];

export const ROWS = [{ label: "No", value: "No" },
{ label: "name", value: "Պատվիրատու" },
{ label: "type", value: "Բաժին" },
{ label: "service", value: "Ծառայություն" },
{ label: "stageShape", value: "Փուլ" },
{ label: "stageNumber", value: "Վիճակ" },
{ label: "time", value: "Ժամ/Ամսաթիվ" }]

export const STAGE = [{ label: "1", value: "Ծառայության ձևակերպում" },
{ label: "2", value: "Սպասարկման ընթացք" },
{ label: "3", value: "կատարման հետ կապված խնդիր" },
{ label: "9", value: "Այլ" },
]
